//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Common.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassTeacher
    {
        public int ClTeachID { get; set; }
        public int ClassID { get; set; }
        public int TeacherID { get; set; }
        public int PeriodID { get; set; }
        public Nullable<System.DateTime> PeriodStartDate { get; set; }
        public Nullable<System.DateTime> PeriodEndDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual PeriodSetup PeriodSetup { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
