//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Common.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClubMember
    {
        public int CMID { get; set; }
        public int CID { get; set; }
        public int StudentID { get; set; }
        public System.DateTime MemberDate { get; set; }
        public SMS.Common.MembershipType MembershipType { get; set; }
        public SMS.Common.CommitteeMemberType CommiteeMemberType { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public byte[] RowVersion { get; set; }
        public SMS.Common.ActiveState Status { get; set; }
    
        public virtual Club Club { get; set; }
        public virtual Student Student { get; set; }
    }
}
