//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Common.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prefect
    {
        public int PreID { get; set; }
        public int StudID { get; set; }
        public int PrefClassID { get; set; }
        public SMS.Common.PrefectType Type { get; set; }
        public System.DateTime EffectiveDate { get; set; }
        public bool IsHP { get; set; }
        public bool IsDHP { get; set; }
        public string Responsibilty { get; set; }
        public bool IsPromoted { get; set; }
        public Nullable<System.DateTime> PromotedDate { get; set; }
        public SMS.Common.ActiveState Status { get; set; }
        public Nullable<System.DateTime> InactiveDate { get; set; }
        public string InactiveReason { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual PromotionClass PromotionClass { get; set; }
    }
}
