//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Common.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.StudSublings = new HashSet<StudSubling>();
            this.StudSublings1 = new HashSet<StudSubling>();
            this.StudFamilies = new HashSet<StudFamily>();
            this.ClassStudents = new HashSet<ClassStudent>();
            this.ClubMembers = new HashSet<ClubMember>();
            this.EventParticipations = new HashSet<EventParticipation>();
            this.Prefects = new HashSet<Prefect>();
            this.LeavingCertificates = new HashSet<LeavingCertificate>();
        }
    
        public int StudID { get; set; }
        public int IndexNo { get; set; }
        public SMS.Common.TitleStud Title { get; set; }
        public SMS.Common.Gender Gender { get; set; }
        public string FullName { get; set; }
        public string Initials { get; set; }
        public string LName { get; set; }
        public string Address { get; set; }
        public string School { get; set; }
        public string SchoolAddress { get; set; }
        public string LastDhammaSchool { get; set; }
        public string LDhammaSchoolAdd { get; set; }
        public SMS.Common.Fluency EngSpeaking { get; set; }
        public SMS.Common.Fluency EngWriting { get; set; }
        public SMS.Common.Fluency EngReading { get; set; }
        public string EmergencyConName { get; set; }
        public string EmergencyContactTel { get; set; }
        public string SpecialAttention { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public byte[] RowVersion { get; set; }
        public string ImagePath { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string LastDhammaGrade { get; set; }
        public SMS.Common.StudStatus Status { get; set; }
        public string InactiveReason { get; set; }
        public bool IsLeavingIssued { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudSubling> StudSublings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudSubling> StudSublings1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudFamily> StudFamilies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClassStudent> ClassStudents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClubMember> ClubMembers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventParticipation> EventParticipations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prefect> Prefects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeavingCertificate> LeavingCertificates { get; set; }
    }
}
