//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Common.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudFamily
    {
        public int StudFID { get; set; }
        public int StudID { get; set; }
        public string Name { get; set; }
        public SMS.Common.Relationship Relationship { get; set; }
        public string Occupation { get; set; }
        public string WorkingAdd { get; set; }
        public string OfficeTel { get; set; }
        public string ContactMob { get; set; }
        public string ContactHome { get; set; }
        public string Email { get; set; }
        public string NICNo { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public byte[] RowVersion { get; set; }
        public SMS.Common.TitleTeacher Title { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
